-- Insert initial users (these will be created after auth signup)
-- Note: The actual user IDs will be generated by Supabase Auth
-- This is just for reference - we'll handle user creation in the app

-- Insert sample loan requests
INSERT INTO public.loan_requests (
  borrower_name, 
  borrower_phone, 
  borrower_address, 
  loan_amount, 
  purpose, 
  status,
  created_at
) VALUES 
(
  'Jericho Santos', 
  '09182156660', 
  '123 Main St, Manila', 
  50000.00, 
  'Business Capital', 
  'pending',
  '2025-08-26 10:00:00+08'
);

-- Insert sample running loans
-- Note: These will need proper user IDs after authentication is set up
-- For now, we'll create them through the application
